### ISSUE TITLE
What is the syntax for castling and pawn promotion?

### ISSUE THREAD

**Issue by ngraf** [azarus/chesslib-ai#1]
This is the _regular_ syntax for a regular move:

```
ai.doMoveFEN({
  from: "a2",
  to: "a4"
});
```

But what is the syntax to announce 

a) castling to `ai` ?
b) pawn promotion to `ai`?

-----

By the way:

Hi, thanks for providing this library. It was the library that was the most easy I could find to get my hands on to implement a simple AI for a fun chess game written in Phaser3 game framework. You can find my current game implementation here: https://ngraf.github.io/phaser-chess/

**Comment by azarus** [comment]
Hi there, i am glad you're enjoying this lib. It was just a fun side project a few years ago i was just playing around how to implement a chess AI that could beat me in my own game.

For the castling question the chessboard class found in `@chesslib/core` should give you the castling as a possible move, and the AI simply determines the best moves by projecting moves forward in a specified depth. There's no way directly implemented to trigger the castling though.

Have a look at the castling move here:
https://github.com/azarus/chesslib-core/blob/master/source/Chess/Pieces/King.ts#L39

And the implementation of the castling found:
https://github.com/azarus/chesslib-core/blob/master/source/Chess/Pieces/King.ts#L78

And for promotion you should be able to start here:
https://github.com/azarus/chesslib-core/blob/master/source/Chess/Pieces/Pawn.ts#L41

Hope this helps. Have fun!

**Comment by ngraf** [comment]
Thanks for the detailed answer. 👍🏻 

I will close this issue.
